# /bin/sh 
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q mThC.q
#$ -l mres=24G,h_data=6G,h_vmem=6G
#$ -cwd
#$ -j y
#$ -N gatk-A-HaplotypeCaller
#$ -o gatk-A-HaplotypeCaller.log
#
# ----------------Modules------------------------- #
module load bioinformatics/gatk/4.1.3.0
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
rungatk HaplotypeCaller  \
-R reference.fasta \
-I ANRA12GbrBR-CL-RG-MD-M.bam \
-O ANRA12GbrBR.g.vcf.gz \
-ERC GVCF
#
echo = `date` job $JOB_NAME done